name: Deploy Ollama Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to EC2
      run: |
        echo "Deploying to Ollama service EC2 instance"

        # Create deployment script
        cat > deploy.sh << 'EOL'
        #!/bin/bash

        echo "🔧 Starting Ollama setup..."

        # Update system packages
        sudo apt-get update && sudo apt-get upgrade -y

        # Stop Ollama if running
        sudo systemctl stop ollama || true

        # Install or update Ollama
        curl -fsSL https://ollama.com/install.sh | sh

        # Configure Ollama to listen on all interfaces
        sudo sed -i 's|ExecStart=.*|ExecStart=/usr/bin/env OLLAMA_HOST=0.0.0.0 /usr/local/bin/ollama serve|' /etc/systemd/system/ollama.service
        sudo systemctl daemon-reexec
        sudo systemctl daemon-reload

        # Enable and restart Ollama
        sudo systemctl enable ollama
        sudo systemctl restart ollama

        # Pull model
        ollama pull llama3.2

        # Create custom model
        cat > kids_story_model.txt << 'MODEL'
        FROM llama3.2
        SYSTEM """
        You are a creative and educational storyteller for children.
        Create engaging, age-appropriate stories that are:
        - Positive and uplifting
        - Educational and promote good values
        - Free from scary elements, violence, or adult themes
        - Suitable for children ages 3-10
        - Typically 3-5 paragraphs long
        - Simple vocabulary appropriate for young children

        When asked for a story, always create an original story tailored to the child's interests.
        Include a title for each story.
        """
        MODEL

        ollama create kids-storyteller -f kids_story_model.txt

        # Open port for external access
        sudo ufw allow 11434/tcp
        sudo ufw --force enable

        echo "✅ Ollama service is ready and listening on 0.0.0.0:11434"
        EOL

        chmod +x deploy.sh

        # Copy and run the script
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no deploy.sh ubuntu@${{ secrets.OLLAMA_EC2_IP }}:~/deploy.sh
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.OLLAMA_EC2_IP }} "bash ~/deploy.sh"
