name: Deploy Ollama Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to EC2
      run: |
        echo "Deploying to Ollama service EC2 instance"

        # Write the deployment script
        cat > deploy.sh << 'EOL'
        #!/bin/bash

        echo "🔧 Starting Ollama setup..."

        # Update packages
        sudo apt-get update && sudo apt-get upgrade -y

        # Install Ollama
        curl -fsSL https://ollama.com/install.sh | sh

        # Configure Ollama systemd to listen on all interfaces
        sudo sed -i 's|ExecStart=.*|ExecStart=/usr/bin/env OLLAMA_HOST=0.0.0.0 /usr/local/bin/ollama serve|' /etc/systemd/system/ollama.service || true
        sudo systemctl daemon-reexec
        sudo systemctl daemon-reload

        # Restart Ollama service
        sudo systemctl enable ollama
        sudo systemctl restart ollama

        # Pull base model
        ollama pull llama3.2

        # Create child-friendly model
        cat > kids_story_model.txt << 'MODEL'
        FROM llama3.2
        SYSTEM """
        You are a creative and educational storyteller for children.
        Create engaging, age-appropriate stories that are:
        - Positive and uplifting
        - Educational and promote good values
        - Free from scary elements, violence, or adult themes
        - Suitable for children ages 3-10
        - Typically 3-5 paragraphs long
        - Simple vocabulary appropriate for young children

        When asked for a story, always create an original story tailored to the child's interests.
        Include a title for each story.
        """
        MODEL

        ollama create kids-storyteller -f kids_story_model.txt

        # Configure firewall safely (ensure SSH isn't blocked)
        # Configure firewall (allow SSH + Ollama + optional ports)
        sudo ufw allow OpenSSH
        sudo ufw allow 11434/tcp
        sudo ufw allow 80/tcp        # Optional: web app
        sudo ufw allow 443/tcp       # Optional: HTTPS
        sudo ufw allow 5000/tcp      # Optional: Flask dev app, etc.
        sudo ufw --force enable


        echo "✅ Deployment complete: Ollama running on 0.0.0.0:11434"
        EOL

        # Make script executable
        chmod +x deploy.sh

        # Copy and run the script remotely
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no deploy.sh ubuntu@${{ secrets.OLLAMA_EC2_IP }}:~/deploy.sh
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.OLLAMA_EC2_IP }} "bash ~/deploy.sh"
